name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - run:  sudo apt update && sudo apt install gcc-10 g++-10
      shell: bash
    - uses: actions/checkout@v1
    - name: make distcheck CC=gcc-10
      run: make distcheck
      env: 
        CC: gcc-10
    - name: make
      run: make
      env:
        CC: gcc-10
    - name: make check
      run: make check
      env:
        CC: gcc-10
